### ISSUE TITLE
Feature Request: Auto-Hide Sticky Notes

### ISSUE THREAD

**Issue by roleoutgames** [mrkwnzl/stickynotes-foundryvtt#3]
It would be great if there were an option to auto-hide a player's stick notes from other players. 

Use case: If a player wants to make a sticky note to remind themselves what to do on their next round. I don't want it to clog up other people's screens unless they choose to reveal it.

**Comment by mrkwnzl** [comment]
In v1.3.0 you will be able to create hidden notes by holding alt while creating the note.
